name: Nix

on:
  pull_request:
  push:
    branches: [master]

jobs:
  develop:
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: fcitx5-android
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build Release APK
        run: |
          nix develop .#noAS --command ./gradlew :app:assembleDebug
          # nix develop .#noAS --command ./gradlew :assembleReleasePlugins
      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/
